new_version: '4.3.2'

change_log: |
  - Reformat all code using Black and make black a standard PR #290
  - Add XNSE as a name for BSE calendar # 277

release_body: |


  Full Documentation: pandas_market_calendars.readthedocs.io

